### PR TITLE
Add Feature/keycloak branch to development branch

### PR DESCRIPTION
**Pull request by mprevide**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
#1986

### CODE REVIEW

**Comment by mprevide** [comment]
Use merge, not squash

**Comment by mprevide** [comment]
I need to fix locust build again...

**Review by cfrancisco — APPROVED** [review]
Great job!

**Review by rascaraficci — APPROVED** [review]
It looks OK to me. 
In the future we could improve the security of REST communication between the services because generating fake tokens is not the best approach.

**Pull request closed without merging**
