### PR TITLE
[DOJOT-86] Fix: Implementing validations when authorization.mode=cn

### PR DESCRIPTION
**Pull request by ademirr**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
https://dojot.atlassian.net/browse/DOJOT-86

* **Other information**:

### CODE REVIEW

**Review by rodrigoaasm — CHANGES_REQUESTED** [review]
Some unit tests are missing.

**Review by rodrigoaasm — DISMISSED** [review]
Approved, but just merge next Monday.

**Review by coutinhosantos — APPROVED** [review]
ok

**Review by Huakson — DISMISSED** [review]

**Review by coutinhosantos — APPROVED** [review]
ok

**Review by MarceloPimentel050975 — APPROVED** [review]

**Pull request merged**
